/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: { mandatorySignIn: true },
  aws_project_region: 'eu-north-1',
  aws_cognito_identity_pool_id:
    'eu-north-1:c4066557-f35b-4046-866d-1e0de3d3c60e',
  aws_cognito_region: 'eu-north-1',
  aws_user_pools_id: 'eu-north-1_2OJCJ3A1D',
  aws_user_pools_web_client_id: '4s5qhfp698mqmca2j1be0d30u8',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
